[package]
name = "neo-clef"
version = "0.1.0"
edition = "2024"

[dependencies]
midly = "0.5.3"
quick-xml = "0.41.0"
thiserror = "2.0.18"
log = "0.4.29"
env_logger = "0.11.8"
miette = { version = "7.6.0", features = ["fancy"] }
anyhow = "1.0.104"
quote = "1.0.47"
prettyplease = "0.3.0"
syn = "3.0.6"
proc-macro2 = "1.0.107"

[dev-dependencies]
insta = "1.43.1"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
