use std::{io::Read, path::PathBuf};

fn scores_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("test-files/lib/scores")
}

fn read_dir(path: PathBuf) -> impl Iterator<Item = PathBuf> + 'static {
    std::fs::read_dir(path)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "mxl"))
}

pub fn all_scores() -> Vec<PathBuf> {
    let mut paths: Vec<_> = std::fs::read_dir("/home/poly/Downloads/mxl")
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .flat_map(|path| {
            std::fs::read_dir(path)
                .unwrap()
                .map(|entry| entry.unwrap().path())
        })
        .flat_map(read_dir)
        // I have no idea why those files don't follow the spec, most likely parts of the data set are AI slop
        .filter(|path| {
            // UnexpectedValue("Unexpected step value: \"\"")
            !path.ends_with("Qmacu9jQZtMucemeJr5cp7qqVC1ByTaKpy4EktWCpcEQG6.mxl")
                && !path.ends_with("QmaHXChzSH1QeNgioRcSEsvR6o55MmJCESj2hNrZeUuVCc.mxl")
                && !path.ends_with("QmaiCD3q3fPygv8QLNfNPCRks2a137qXv7V9AfBN2GfUgf.mxl")
                && !path.ends_with("QmaLDSNyjQhCTe9z6Qw4CPVUbKQRyxBEp3YQMMqxtqx1NZ.mxl")
                && !path.ends_with("Qmat3pqdUyNwcjikVbi4zq3oasukX8DvgfENBbBBmNH2qY.mxl")
                && !path.ends_with("QmaVpecYiM3DRLdGx7kvTwuAoveGuf8KindRgGrxdwhB4A.mxl")
                && !path.ends_with("Qmawi2RLrg67QXeRTbUENEVxUFNT7zByTxyZHEPoJGMhDg.mxl")
                && !path.ends_with("QmbbgAwwZ73tU4A9ZxEfT1eqFRTj3NX6TDEurK6KCT4196.mxl")
                && !path.ends_with("QmbjMAtnHqPG3iSY6eaEpBumMe65n2pJP3ef6uiupAA4Q4.mxl")
                && !path.ends_with("QmbuFqA9aZjWgrrrtxy5rvuojeTy3rjKqpuUkX7Jj2Zdcr.mxl")
                && !path.ends_with("QmScHanBsmnN8sLu4NukJBZkzxUQQ3DAA8o4GvufDjfUZc.mxl")
                && !path.ends_with("QmSEF4pS7Y1sxQTwLWiuQJ31LBf14ZopaNYq5XL2XxxW8v.mxl")
                && !path.ends_with("QmS3uP2eodhqAekB32ncbzRARoJzNhCG1DcPdQtuyofRtM.mxl")
                && !path.ends_with("QmSQ89KAxrDrvq3gss1KK7nTwiR8uUWLQtMaw4uX4bX1Hd.mxl")
                && !path.ends_with("QmSR961S6Z686rWJXk1tzTD5PeWJsTM5StZ9PEMpwFbQZ7.mxl")
                && !path.ends_with("QmSTvwxfRNpGA5SHi71Giy1bq7JPuHMwAa53Lvpzjv7vtN.mxl")
                && !path.ends_with("QmTJUDKfQRrdvnDJVJT8iPqVXqnkSAW12sPXqzdZ9xnHwk.mxl")
                && !path.ends_with("QmTaXYcKzAMoCDtWts4HozqSsdVv8QHt7jcXWkwc9s2v1B.mxl")
                && !path.ends_with("QmUibZzqFW7AUYq9mNk9AWx7Z4R6UmAzTbSm82ermATnis.mxl")
                && !path.ends_with("QmUKGAiS4wHYnXCnXMHhvvA2qHHMmVTzvGnKRxbGDa3Y58.mxl")
                && !path.ends_with("QmUocTSmWQMre1gnn42Yd3N34i28xSYkKL2FmwUCnzixjx.mxl")
                && !path.ends_with("QmVC91sntTB5QB2JFfouUATxwfu9xZtgEV9WmoTbTwMz6X.mxl")
                && !path.ends_with("QmVDsDmRSfzHA9bQoxu54aBCs76YEYgRXchLfVTtG4AtkZ.mxl")
                && !path.ends_with("QmVMMuJxzmVkTSo3YpbAyQNPrkjWUqGomc4fNFcutSiMSR.mxl")
                && !path.ends_with("QmVSsWtp487WFnTLmkV28k5E1r8TngTRGFWM5HvH6oCD1G.mxl")
                && !path.ends_with("QmVZpMxLUfhZwJKpY49ym4SpsUyxGS8eQSepp24Jghknip.mxl")
                && !path.ends_with("QmVawS3KnbNhuDTk2EMdLsXd87tfHyXXhVWrBWcVzrVP1f.mxl")
                && !path.ends_with("QmWCU1VW8nfm7sWPtYXD3QTckEZK9cGJBN75X3JGYnH6kL.mxl")
                && !path.ends_with("QmWoLBsm1zCozpoChTDTemwMDeM4Yay9UCwvF5ni2w3De8.mxl")
                && !path.ends_with("QmW5AGZhQqbuhGMXX4CA9adZ5Cngd8DcXoH1HrpahRyC4V.mxl")
                && !path.ends_with("QmXJNxkHdRX66XN4T83BLXebFctv3Rf8kBm9UE3YBayYXE.mxl")
                && !path.ends_with("QmXqbDB8pKooe7PcvMrMdGt57FPAa7Vswf9uSjusUeuHMc.mxl")
                && !path.ends_with("QmYPvPpK2e57cSFCdNyfcsHGA7Q5pYjQRbgsQAoWVAenTG.mxl")
                && !path.ends_with("QmY5TLbhZQhCzK5MMyUkPAByXGG2Dy7LeY2Zc2AmhxL75C.mxl")
                && !path.ends_with("QmYrJKaoT1dpvwha1tr5qvUHp3o9dvUqY3XZDE9mkXabK9.mxl")
                && !path.ends_with("QmZBRh2XwhewF8Ya8R47Ew7AptfnX4y4LLRRSG29SRZwX7.mxl")
                && !path.ends_with("QmZmgQ2zWzLheP1XfcP8CTVJL2sp3vceQDbryY8GtcGpA1.mxl")
                && !path.ends_with("QmZVDBNZyQPfyV4oowVBrH9QS2bXwRSLnPeLARZqX6dAR9.mxl")
                && !path.ends_with("QmZwGMMKJzk7yc5a1PoixuosZcNASDjZxTeouXXJAhKwTm.mxl")
                && !path.ends_with("QmZzSiuWfCuZbCBNPEqDisSa2ZZVwryRS4VEutooNaDkHd.mxl")
                && !path.ends_with("QmckKLukPDexDdfzQ9JHfonmBKkPR635QnvNJBbtf4pANX.mxl")
                && !path.ends_with("QmckhfFHkDa14BcTckEiW34GCn5T5zEWnV1NaA4pp9XP5T.mxl")
                && !path.ends_with("Qmc4tYEFbQMAkjnrx1ire8QfEazTN6uqNUwGmSUeqs76Bm.mxl")
                && !path.ends_with("QmcuPT2ruvs3CUQcVCZQWiYfqWrjjku4eFwLeBz2rtSwfS.mxl")
                && !path.ends_with("Qmd1VdRnZCY2RGjK1zWTvSGybGSxPHHjTDf8a9ZYDF86cN.mxl")
                && !path.ends_with("QmdLRWUW7BL4rCnAH1F31s9FThDAqiechngpBciJ8gP34s.mxl")
                && !path.ends_with("QmdvCvLcbJw2YLZdxt63b1YRNMdLGAGnAMrEx38Lj1zzqD.mxl")
                && !path.ends_with("Qmdw22GUzBWEkt3TWwdVKmus8umcX9XC94thj45gw2Jnuu.mxl")
                && !path.ends_with("QmdXqsYumkFovt5SgX46oJMZpNdzEB9EbzZiDicGsmghoF.mxl")
                && !path.ends_with("QmecFvEKVd8zgHstmbN37PMbzXA3B54xNVEeKuxsJJsShb.mxl")
                && !path.ends_with("Qme3U1f7ye5gzUctEiS7RYv2BCjvKZNAgmzu44EHLusCPd.mxl")
                && !path.ends_with("QmeGBSweJihwTQ5nM1UFBUG7jYtzSkemnKYr1JANMHTMuh.mxl")
                && !path.ends_with("QmeS7SQvgkKioAcSWPUu3XDGeGMUUB4sovyz2nGybvddTJ.mxl")
                && !path.ends_with("QmeSH6DHqb4MXfh8FVJWZWChcUsKSEqbMeUZj3PQaSUQAH.mxl")
                && !path.ends_with("Qmetz7iuDNRWSQK3XWTQ7NBDFb9ca8E2wznYeLNfxMzj8P.mxl")
                && !path.ends_with("QmeVoT5ZiDJm9QzYRsLkq2zjH6wjA17CTicqHrPQk29HFN.mxl")
                && !path.ends_with("QmfMsY427fE1yDnPTc7Pc8cXWaanMipxJmT7CrutnLGYFV.mxl")
                && !path.ends_with("QmfYxRdQMEYDwwPJTQ6QaBCoJtoKAj3yg7879cLbxEbX9g.mxl")
                && !path.ends_with("Qmf8pf55SQeW138FR9LStFQF5CzeMrdff5ZaYj7VW3hA2z.mxl")
                && !path.ends_with("QmNjKV3z75eAwcyV1va5hhLQtqTpdjqPsrjgYkoumAGXti.mxl")
                && !path.ends_with("QmNpsAvdZsdMzyVw6ibj4coYo9dBYHf6zhFqdqm3L4MY6Q.mxl")
                && !path.ends_with("QmNuGUt9TFMBGcW3TVbb55PjorRR1bhjH9f6VToLUpYZaG.mxl")
                && !path.ends_with("QmPh7JpjNHyB7Ms7fq2iEM47RW9kAnCtewPgvC88Cfmy3J.mxl")
                && !path.ends_with("QmPhmwZPJHAUw5V6MdzdUVWrnoSsm5QWwgNvnxortxFtxy.mxl")
                && !path.ends_with("QmPkUgDvqxnYwffkw1PjU8D4aXokN6k6D4HS3FnLYHTkzZ.mxl")
                && !path.ends_with("QmPwFQqKByiUN9hpNY3eKq4b4ZjKWr8y7dgvDVkDLKdiZ5.mxl")
                && !path.ends_with("QmQ1KGYrMfEt1JbQcDvCZKBddyYEk9eUBUT2HoPW2VtavA.mxl")
                && !path.ends_with("QmQ2eg1tdFwFdoFRo464cHujPxcY2T31k9ETsDKWVBTCLV.mxl")
                && !path.ends_with("QmQgZC74sCKuWKJVeHLSP6LVMhg62WzpRm5XH6SFKYwJk7.mxl")
                && !path.ends_with("QmQJ31ynfcnUPbiDTjamNyfKE7wi6JNGJYkfPGPfnxKd9C.mxl")
                && !path.ends_with("QmQ4FoyoXtFMiw8QrC2NZCmgDaj1wi7PJwkQie3sNGKuVu.mxl")
                && !path.ends_with("QmQzezkZCE3Y9Jifg7cCuTrS2KMjwkqQe27FZWMA2x3KaP.mxl")
                && !path.ends_with("QmRJWypJzPyEs4LdXm3McS6bcVyXbxtTjLNimUE5ecPy78.mxl")
                && !path.ends_with("QmR6YXdrWG4KEUR6djfMZhPTed2b81S5ucHxmkhHjvxxMK.mxl")
                && !path.ends_with("QmRwCa4Jw4ACi7dGkUtUZ7deRcEyHXJKybYemx7EiUctDk.mxl")
            // UnexpectedValue("Unexpected step value: \"ø\"")
                && !path.ends_with("QmaCohYGQE2eQ1qQitrAaTD4R4QLzZQLedMvcmAc17YfnE.mxl")
                && !path.ends_with("QmaJ8ta5r2p4qA9FBHMayzjMT1bDDwxSRKcTp7K5ve3AxL.mxl")
                && !path.ends_with("QmaWwYYVsVL2QqHFmi8rUbiEm9akqyeEENFnqCDVfbHcTJ.mxl")
                && !path.ends_with("QmaXDACYkynAuGeEj9btTXhEJ3YXzy663K96wpnYypNazi.mxl")
                && !path.ends_with("QmbFgZuT9eXt4s988VFkkULnXUUzUPLacohapmLKmRPHQm.mxl")
                && !path.ends_with("QmbURZpavKxUkuKCgXPSYwHS5zktfs4YWBBkh65KQudVDR.mxl")
                && !path.ends_with("QmThLDRx9eP1YYWqTp98gy2Vmc84cHCYKqy3fE2S3ci5Xp.mxl")
                && !path.ends_with("QmV8T3bBZAGdjEPYjaq5ssSUBbxois9agdYEHUL3dgVXGB.mxl")
                && !path.ends_with("QmXMqQS1VXoCGvMyySzTxsz3NXC68beu7cGNWCggyMcz26.mxl")
                && !path.ends_with("QmX6xEQuoM1cr3gz9z4TxUxYGBZebtCU4HA4dE8NygtiD7.mxl")
                && !path.ends_with("QmYWY5q3xRSGxWne79pQp58pbkAikNgZPt68r2Hd9oME8D.mxl")
                && !path.ends_with("QmZqHQpUy6SuTVdCdvKGtxtMrycAHFxVFSt8LmUeLRtcj8.mxl")
                && !path.ends_with("QmcoUU5GzHiZkKeEUfC1xNBXjauy8xqkbMxyJct8JRSXyT.mxl")
                && !path.ends_with("QmdBHiPZsG5idGi4UvBg76MU2VGhzQMR7hLXW8DWdkz2Kz.mxl")
                && !path.ends_with("QmdRY9ZyrnaVUGgU1ZrRKuErvES6L7bjE9xC65wq7X7mDM.mxl")
                && !path.ends_with("QmR13juVDv1NtrPwxT1Vv5X2m75cZnHiZEKPeVESDzhvjc.mxl")
                && !path.ends_with("QmRL8YpUQ71tQH8GJpp6zMty9hLen5377f1eHN5ApHx8H8.mxl")
                && !path.ends_with("QmRTYFZ2SkBWbqwDpAqfCsZiou1KGVUVAogH1dg7z7RUNG.mxl")
            // ParseError("Invalid u8: \"-1\"")
                && !path.ends_with("QmaeVS5pxjF4cYYyBwYhjcTqVQ6W3h1rCUBYQMqiFiGJUm.mxl")
                && !path.ends_with("QmaSw544wzzqi6SpgPveWVpR1YrjKjzBcSd2JeqwgsGfox.mxl")
                && !path.ends_with("QmavyGmPkudZXfFfDgefwJWoCzTeNNwp5W4ByRDiXvReag.mxl")
                && !path.ends_with("QmaWKzAB28pMbBZZxb5jqwcdfu5FekzJHPzKSpjf5gJ4ht.mxl")
                && !path.ends_with("QmbbXPcyCCcajnMrs3sw8FfC862SyRgbhuJSdiz1pm1mxF.mxl")
                && !path.ends_with("QmbgVu91CEXRaxv7RagYoi98DEzosZCtkGFKR2xQSKWKQZ.mxl")
                && !path.ends_with("Qmb7PVipsSuCLk8FXrnnWd71Xx64FQvd2nAuztmGjSWiUx.mxl")
                && !path.ends_with("QmSA6vMsXrejTZ8eNEvUmVJiRSjy8eCkbJs7KGAGKDyRL9.mxl")
                && !path.ends_with("QmSAuD5PBrD6Tmm7Toapn7TMwcJ36smJGf5Ry7TMWp4oFT.mxl")
                && !path.ends_with("QmSdEbcpUQFNRwH92QqRqLEwZ5uGbztEu62LMUaBSRk9dd.mxl")
                && !path.ends_with("QmSeyhZjXmZUo4KoucSkhkyZMnPu7Q59dnmgFh9kUY98Pp.mxl")
                && !path.ends_with("QmSMSJjjK5ntsnSPjZEtaXV7dVGPqH1sYcwoFSR7d6WYhi.mxl")
                && !path.ends_with("QmSPehNevbuqk962JL6NfEAsTpS46viZVJ1Nw958BPyT9m.mxl")
                && !path.ends_with("QmS6UNWW99KQmcRYXYdTKedX7jjU47WSuZaLexdVfBx8fc.mxl")
                && !path.ends_with("QmTgEpowKhm2TwUwgdhU47S1LuHh3C3RYCb345CBXTqqiB.mxl")
                && !path.ends_with("QmTLSFdETUnfQQTU2drh8HWrPaqikDgmjVZY49bqcCrMPx.mxl")
                && !path.ends_with("QmTSGGz3XRC7macSxU45FvrurJQ6dVE2CM3QQSdPUJNqWg.mxl")
                && !path.ends_with("QmTStPWVEJt5RzCJE12P7CwmDjC6fwX76mtQBiUpVrMVK9.mxl")
                && !path.ends_with("QmTaqtANZLSDJdfqFAsRkr8tmSbvy1cgyNoQok2wMRQThm.mxl")
                && !path.ends_with("QmUBJFXFDYCnuM74Hz8iikffki3fm6PX8pZgtDnVtW48b8.mxl")
                && !path.ends_with("QmUdK81u6XTRQ2h9UDGfUf9XQtamEirQpW8k6MzKJyNwMo.mxl")
                && !path.ends_with("QmUj3dvhPteyv7TosQrFhNP9AEXm31mtV2t4wTkB1oLqtH.mxl")
                && !path.ends_with("QmUwSRLQbSjuj3Qy3E6CPnrEZ2p29uQe2WxdTPhs6NyEvA.mxl")
                && !path.ends_with("QmUZ7hipADGvZXiURPQF3bZr55sk88b3WnpTPw1FzeQBma.mxl")
                && !path.ends_with("QmUa1codRrgC8bbs9fPiBoCrsajEauujxrpx5jU73qMcrE.mxl")
                && !path.ends_with("QmV2pHMHet3qK5N3wGn5otWezMWfeNQuBYj5Kp7LGbv1MM.mxl")
                && !path.ends_with("QmVAhS6aRKVqPLHLRptE4ACy4i7vt3YpWDg8seDSbxahXg.mxl")
                && !path.ends_with("QmVjXTFk1o6FVzyXotAQhq9Lo3kqcCe6yKwsHrQ3i6YLEp.mxl")
                && !path.ends_with("QmVKc1aM4Ez6x8jXFwN39TN3T6P3hQZXTuag6QJvhTqTxh.mxl")
                && !path.ends_with("QmVYrUQGtstQihGvz7Yr1xYjaAZCFKKFN28ZZGm41Vttx3.mxl")
                && !path.ends_with("QmV8GFtxNX9aTomf9e5PcZ9Tj7PqW9LFqwZSg8t56MdmWQ.mxl")
                && !path.ends_with("QmWFSw8D5WSrrP66Cuk6uzyxksphMYXLeY95Nm5gPik2Az.mxl")
                && !path.ends_with("QmWiQ2re6FuVn3pYtyXpQhRF3FnthTjNaCMzZqo2UgtJKU.mxl")
                && !path.ends_with("QmWai56FXKss83qiqmtS25brdxW7wxWM411mi37WutZVrt.mxl")
                && !path.ends_with("QmXDDuiwL6Ut54Lwmi5tB5YxVA2wAodACtpi5tsdT4oD8T.mxl")
                && !path.ends_with("QmXr1Y5mpWVCDEG9N9zM1wXqzdFAb7RAN3ymvVnpRAZtUh.mxl")
                && !path.ends_with("QmXXy7z89Mwgd5vP7VoLnPy2uB8GYwTwWs7LjTrvm72acY.mxl")
                && !path.ends_with("QmXzc99eXMfzG3z1wzu4MWRLm6N6WYUk1XgBEpt6xFzk1G.mxl")
                && !path.ends_with("QmYGZcYeRLMrnEprzWg7h6w2m3yS3M155x9ywAni6KNsyv.mxl")
                && !path.ends_with("QmYKPiDpqssxUtzRQsKkWyUYN7gq3qYdj5RYfU7eUNTT9w.mxl")
                && !path.ends_with("QmYLCEDMXcKMW1hVDGEBudx8q1UFwcyuhPX9mFW3ZuDpKM.mxl")
                && !path.ends_with("QmZBec2vExwRCqSheGyf42CVEX1o8PSs5PLatqSFwh19p2.mxl")
                && !path.ends_with("QmZeWJtw5s5E8Grc4ngc7nLFQ3F2enyoxx18ug2g8D3N9J.mxl")
                && !path.ends_with("QmZFVE1j7AY4aZygSaiSmzqGLyJpfACFrRMKp38ujqnjte.mxl")
                && !path.ends_with("QmZmVgGLNTfW94JzeTceekouTrCkRrWiKkpowiZNZF2wzY.mxl")
                && !path.ends_with("QmZqZphrsjWqzGugk2DMqbV8KfoVoo6z3Y9gN1zdNBJ2bj.mxl")
                && !path.ends_with("QmZuV3jHWvcSL67u7g6aTrKeDLswQa5aiYKFcRvZmmTc3P.mxl")
                && !path.ends_with("QmZyQCZ8zeAJqKJEfwN1D8gBEiaWJRDZbkdgjZiUq7piHF.mxl")
                && !path.ends_with("QmcBG2SuLsbNBzvPe4iZS9dsaJ8tmHbb9A2s8D2MhJBaK2.mxl")
                && !path.ends_with("QmcH27kDZE6WEvMebsQVvJP3iGU3MY3KDShQuwycpZXMqr.mxl")
                && !path.ends_with("Qmc4eENL7exmbhsnX4p7tBPyYQ7kcTFDZDM4bHi4woQSqT.mxl")
                && !path.ends_with("Qmdd7eBdq6oJXE7btnCVwi4m7gBzGEVZXQYtxb54b1qTn6.mxl")
                && !path.ends_with("Qmde8RevLswxpFnAVHssgYrEiCJ7CM78kzvv42xuP6hS4U.mxl")
                && !path.ends_with("QmdiQXjA9ebZVvsL5GosLJkWjmujr1KkUy6MQm7QheDuYH.mxl")
                && !path.ends_with("QmdV7VwM2Kv4MeQa3XMejUVnTNHfFCgdG96Jj2gTeXzXsP.mxl")
                && !path.ends_with("QmeDha2g8qDwCTuEX71J9McH8HMb8eJh9TNAKNMqeGDh9e.mxl")
                && !path.ends_with("QmeGbbvtEDcQpMFtNVvfBXw7d3bT9ocFnYGcvdVzHNFL4a.mxl")
                && !path.ends_with("QmekJ1RCHze3VFFePomC2KVmYqQLmogHFFuXkmM1WCYLHh.mxl")
                && !path.ends_with("QmevCUcue2WcqDCvJtct7CcwiGfvUxJAKcPdXEzCHgabnU.mxl")
                && !path.ends_with("QmfCUhkrAsHDsEQQeZgUAdndfPvseG4rHZvkncTJXMELDa.mxl")
                && !path.ends_with("Qmf3Abg2MfJV26xwz2EbwcGUdsnj9EWjd5NsxWm8ZdrTvM.mxl")
                && !path.ends_with("QmfG6Akm7SCgZVBroRmDwajLYu1aeTXR7b6u7jjKnX1GDA.mxl")
                && !path.ends_with("QmfMFpWGdrGJ7zsWzraXFd3Sc8tKqh6oiZ4PLWrHwwU66p.mxl")
                && !path.ends_with("QmfRLRNqsnHNHGEjxZpZGnRA4S5nJ4CBR7jSeagxWdv2t8.mxl")
                && !path.ends_with("QmfXRMR75U2NZS8x7LLUPH8SY87G2AUrTTHemcgRHAWHtT.mxl")
                && !path.ends_with("QmNW7Bo6DVVF1HUYxRJsnFD2zbE71p6fCaE4ZqhZgkSYP8.mxl")
                && !path.ends_with("QmNyhW1q4Q6CA5rzWnt1RUwEZ3BsFAzDrhRPzhkrw2GST4.mxl")
                && !path.ends_with("QmNznN9MR6Q1ZPnyXRT76y3hLgbbiNz6jgxmYDA99z4rtC.mxl")
                && !path.ends_with("QmNamu8Xfws3zNzBCH5yzMuEmy2gEgfbgnPRbYHyfeqWuU.mxl")
                && !path.ends_with("QmPJwrVXMj3CdNZA2y3tmeqh1FVUywmQJwEYnvfG8yiGzW.mxl")
                && !path.ends_with("QmPwAdmqqJ9vZVaPzGAR9qRdzxBM3yWDxHn8LqAmiaUf6C.mxl")
                && !path.ends_with("QmPzpeuavH1S1Z1j16sDnxngybsev2XHx8DMLjDW2h1P1C.mxl")
                && !path.ends_with("QmQRexwHTV4LX2oumfEX5g9H8iPZVzhM6dtwkUVXEyFnHU.mxl")
                && !path.ends_with("QmRbpFEfSGRUNMfB4j5R3KnbsXcJwHo5W494QycA5R9oP9.mxl")
                && !path.ends_with("QmRDiPbmHpQJNHdgLisEBKmJ3hwmarwMkeDe2bUhajSGtM.mxl")
                && !path.ends_with("QmREZSfNnfGg91oT6DTHTRyJnw8SLwpqe5tw2T5dF8Q5Q7.mxl")
                && !path.ends_with("QmRUUec7UqvnmSwH4DqJppK7oJ3KpYoHFYJ5EXerNEoYYq.mxl")
                && !path.ends_with("QmRZVaF2MzXDePaiNUQRTwfGJQBoZ3HzqM6Zmr5rHQQcuj.mxl")
                && !path.ends_with("QmR8bS5Fj9JXRZ7j7ZiYbTe5SkYL15vkWPRmPHmjuGrTwt.mxl")
                && !path.ends_with("QmR9rTNRXwFHHbSTksRpk9WHUngBXNcJgP88QeRdoYzRd4.mxl")
            // UnexpectedValue("unknown harmony kind: ")
                && !path.ends_with("QmbASVSMGZrsnxpZvmTvc3DHGpjFP4CjbePzZxmXtdYS1K.mxl")
                && !path.ends_with("QmbgHkbrLXpxjyH6TdYDVSY3Etqf96tja7q3Eq5jc2cYdm.mxl")
                && !path.ends_with("Qmbhz5mUg7Br9v2oyQmt21jAPnp7ibssH6VbCyVmwYQZcU.mxl")
                && !path.ends_with("QmTcyUryUdRkvzpVbxL79Enx3HsN7bkJTJyv1g6nphMy7x.mxl")
                && !path.ends_with("QmV3nFy4GvpH8Gc7HpJSpGYkrgH1tcYBoNrQa5A1utKJzs.mxl")
                && !path.ends_with("QmVYitSeVFFUqg6BZRsLyakx35ffP6sXb3vyJqqcjoxXif.mxl")
                && !path.ends_with("QmW47j7CZfF9MCNjMGQcX5BHEK4P6PMtiMTNupTJpGtESM.mxl")
                && !path.ends_with("QmXBEU8FGJZymqyvWMWba6KjtoVunxTPe4kfV3AXnzVors.mxl")
                && !path.ends_with("QmXD8qeUbiQg9fVqBTLuaRc4NDXn1T5Z88HHoGXGAV1vLB.mxl")
                && !path.ends_with("QmXH9ZNRa1riFK88HtTUnuEwEDpP9dJWEiCWiydA87ZHgZ.mxl")
                && !path.ends_with("QmX4TkitUT6Fr3TZBUbyWwBXRpAar8vwDAHGPZs7x8Ugwz.mxl")
                && !path.ends_with("QmX4fM8MVKTrxfHeegHF3odtGjCLP3bstjLnqABwopYCko.mxl")
                && !path.ends_with("QmYeKSRPncGCK2u4W5y2YkBK22XwfjSvFhgmFNB7gtKfzp.mxl")
                && !path.ends_with("QmZe29YW6uioehnCa1ZVTQxTue4AYD4X5WbsdjepMq24t6.mxl")
                && !path.ends_with("QmZ3vfJw1vS5Me9KDoUYSm7RYU4FYSAwioiFHbtogRihgd.mxl")
                && !path.ends_with("QmZtVTHeNzr15w9H6JqAi2eavEWpNNVXE3bLs29GbcGTZx.mxl")
                && !path.ends_with("QmZWL7A7YjKH9qXNhGK6fVHkuKdyenVTMsr1Wh739YutdV.mxl")
                && !path.ends_with("QmZyXGoSzjb1RRoNRBn195pTFsY3LtUGhhtZ2cKiFS3ZQw.mxl")
                && !path.ends_with("QmZ7SQyaYWFiaMiz9gJRUVfAycmVKdFotnEyBAWaZT7mBU.mxl")
                && !path.ends_with("Qmc4oPnENyGYJhLcPS3QYYKjjW59LJCtpqKhNfboMbC4mh.mxl")
                && !path.ends_with("Qmc9btBBGmfYrGwiDvCjas9qqsdyk4EQFTwqkc649YxLBL.mxl")
                && !path.ends_with("QmdZ4fF9xWoWxzvvtrnnMzcG3zJZKWKuizKskcA5tb5Z6U.mxl")
                && !path.ends_with("QmdaHo4RZRggQTwedFkWo3CBVdRd5oTWXQoBUfG2dmnGLQ.mxl")
                && !path.ends_with("Qmdatq2f7ncmDTBB2QY86PXPgMyuiaHYT5ShXbjf1JNHSe.mxl")
                && !path.ends_with("QmeE2hzTsW8F21LL1bvzNMVsh9KkpucwPV9Vr7MUsgUthb.mxl")
                && !path.ends_with("QmNszpY2zuJiDZFyLg1ynayAFAWVREa7dfdFmosyt9Lqn3.mxl")
                && !path.ends_with("QmP1YvhRywZvDFSQZsBZzFxcGaxPFyA6y4obD6ESimRnVA.mxl")
                && !path.ends_with("QmPbo2bC9WPXQvsgJdSKFuJquXxd3ru4WgHzkKzaoMeJji.mxl")
                && !path.ends_with("QmPkHi7q5nyqqBuaoKVBAbPNXr6SNUWSF63M2FCkVcJu2Z.mxl")
                && !path.ends_with("QmPKoc1mQEcyYJq5rr8sQK1RuViyt3aKgAuSodLgCiUc5m.mxl")
                && !path.ends_with("QmPL8PREh55CticL4n1pQZbT9WXZ87QP33hT8j2qxPcxkX.mxl")
                && !path.ends_with("QmQdYEbPtSSwLHmpVPzEJsXuphrdADKB7CakWwfBgwYk8m.mxl")
                && !path.ends_with("QmQLncrAJVJX6LApiiGCdBbfVkFBH4CmsL6s6xdAW6sN8g.mxl")
                && !path.ends_with("QmRyAkLn9BWwsJfvsDNbxAz8nFxFbQzNxk7ov6TEVuHhi2.mxl")
                && !path.ends_with("QmRZRwwjVyppRUYXSiTXRPc4LukvPrN7Zx59CSEneDif9y.mxl")
            // UnexpectedValue("Unexpected step value: \"?\"")
                && !path.ends_with("QmbY8j8rA4eRKMH17RDmWvS1E9wGHZfaQi3cezrHAHvg5W.mxl")
                && !path.ends_with("QmTunuosxWyNrjohVnu9zCHaW8giqqoDVNhxCQsDmEct5U.mxl")
                && !path.ends_with("QmURL7At4atkd2CtDAmqweh5rCtk6oNqDCT6v1nTrZw3cG.mxl")
                && !path.ends_with("QmVpb4QZRTQuWhpN2dj7JcZLiJuWaHCchUF3yeUtZ7FRL9.mxl")
                && !path.ends_with("QmWbfKEjcoAedMzkSGURVBTdRwTGxaJe9MVHqa7qvhwBZS.mxl")
                && !path.ends_with("QmXBdZYCYU4VKB7PpsYqMetSvESy3rWWkjWLqd7TdkUp7B.mxl")
                && !path.ends_with("QmYc4Z7Cwqzj8kSupj6gmqL89xYnsHCGdmt8vvRZPSWM4w.mxl")
                && !path.ends_with("QmYgEa5r5hrw5BKWtb2dhScAwsXuqpdGoER9wtKNSvnJk1.mxl")
                && !path.ends_with("QmYvtAYY24yxMZPDHciYZmwu9CrWg7h1ZohekjdUm67JNZ.mxl")
                && !path.ends_with("QmY9VJakE1HsRnSGYiJzBPSpiHSfn6Psxf72CFSpNfvz1s.mxl")
                && !path.ends_with("QmZ3EgD2P5Y21pPzQXe2p15ffXYkvzzXTCk44B4h3UBYxx.mxl")
                && !path.ends_with("QmZF7Sb36xvDkGdK7TgQVr6jwZCXRkYSp5TFSf3fNsZaWU.mxl")
                && !path.ends_with("QmZLMxE7zAC3KWghusAS78SPAopiKnTjEz5FWPpxsPJdDJ.mxl")
                && !path.ends_with("Qmcj8GVnvZ6ZJzQCnaWqpqjWzBWvnLQMtEP8rDBhEFJSK2.mxl")
                && !path.ends_with("QmdFJAzz8UjBfRh5Jue8ztUw1UVL9qVyR3JrJVXUYtMgyr.mxl")
                && !path.ends_with("Qmdt581K3mixCDP5ZXQ1Mh4HyufT2rzzTxoR1b1r6aaTrZ.mxl")
                && !path.ends_with("QmeTxzwns2gJcmd9r4qLUfsdSPQWsxa7RiBUUxiBYjDTCP.mxl")
                && !path.ends_with("Qme8nCDHHfFVNhjXq2Y8gsNRkVXSSkTtsJ3iouLKjSS3PN.mxl")
                && !path.ends_with("QmQbx45ig5NWozxmNkKrCW7w2cN4Jb6tPhc5nTd4xAC68n.mxl")
                && !path.ends_with("QmRBbFh2xydWTfdHTDGBnzGYY1e31wtrTey2QRW4gLZsqJ.mxl")
                && !path.ends_with("QmR3aTR2VvEvNutSqWjsnzR2hCNqYGsb5HQiNCgUjWqd95.mxl")
                && !path.ends_with("QmRvSPQZoViwrKpE1TiyFD9Pf1UMNaBGcHQy3VqzFUa7vp.mxl")
                && !path.ends_with("QmR9rgTSiQUYBmVrgmUR8sjbLPL9KyxvzbmjKjf2AjZpuj.mxl")
            // UnexpectedEvent("Invalid dynamics mark: \"z\"")
                && !path.ends_with("QmUJHLmAffWcuSZTwZVQhAZZVMJKs3ttgbRC7Ly1gLFPz9.mxl")
                && !path.ends_with("QmQPfvhHM1wK91kTdR66UQUdzapTQnHFJqSt7qYjGUq5ak.mxl")
            // ParseError("Invalid u8: \"-6\"")
                && !path.ends_with("QmU45SM3qpU4RUnRLEY9yeYqs3QPVrdqxdWqySF4KV7Gi3.mxl")
                && !path.ends_with("QmQx9z8VzqaybWvQWHRzNoou27CoNxttJFVYdS9shQyXo4.mxl")
            // ParseError("Invalid u8: \"-22\"")
                && !path.ends_with("QmUwsvNNdY1Z85PCwdRnvyYeUCPLP4VLmsTW19EsVVpTzA.mxl")
                && !path.ends_with("QmVUQyeiPhDqxum437BSf6fjZ6w5S3VBVEanH5QFpvsuMd.mxl")
                && !path.ends_with("QmPa3tkyCKYVVyCUJuZ5PYaJTBQyEgH5xEeFnL1y2Q3EvE.mxl")
            // ParseError("Invalid u8: \"-38\"")
                && !path.ends_with("QmXo4rd9DAcbqookAZqtQ1VdkczRcaUkDLezmerHBrRXJs.mxl")
            // ParseError("Invalid u8: \"-2\"")
                && !path.ends_with("QmXwHx9eL6dhhsr3kxDkbVuAz8yLT7TK6fz7XqFvoGMdWb.mxl")
                && !path.ends_with("QmZSgpiTbQPRwXiSHwreGRCFNWPR15hXHUQGKwu3ZYhmwE.mxl")
            // ParseError("Invalid u8: \"-44\"")
                && !path.ends_with("QmcZyt5k3CaWKHkc8X1TiJBghrnQ4vvBaurxseCkVVHcqS.mxl")
            // MissingElement("measure")
                && !path.ends_with("Qmduw5cLMjA1GnyjVJ9z7gQy3ZmGAiUgokMwGZ5ryUeAsc.mxl")
            // ParseError("Invalid u8: \"-8\"")
                && !path.ends_with("QmfMWoCzcmGQbstt6NXXBhey2CxZQ5MDN6j1ivN6VHfN52.mxl")
        })
        .collect();

    paths.sort();
    paths
}

pub fn extract_mxl(path: impl AsRef<std::path::Path>) -> String {
    let file = std::fs::File::open(path).unwrap();
    let mut archive = zip::ZipArchive::new(file).unwrap();

    let mut container_xml = String::new();
    archive
        .by_name("META-INF/container.xml")
        .expect("mxl archive is missing META-INF/container.xml")
        .read_to_string(&mut container_xml)
        .unwrap();

    let root_path = container_rootfile_path(&container_xml);

    let mut xml = String::new();
    archive
        .by_name(&root_path)
        .unwrap_or_else(|_| panic!("mxl archive is missing rootfile {root_path:?}"))
        .read_to_string(&mut xml)
        .unwrap();
    xml
}

fn container_rootfile_path(container_xml: &str) -> String {
    use quick_xml::events::Event;

    let mut reader = quick_xml::Reader::from_str(container_xml);
    loop {
        match reader.read_event().unwrap() {
            Event::Start(tag) | Event::Empty(tag) if tag.name().as_ref() == b"rootfile" => {
                let full_path = tag
                    .attributes()
                    .map(|attr| attr.unwrap())
                    .find(|attr| attr.key.as_ref() == b"full-path")
                    .expect("<rootfile> is missing its full-path attribute");
                return full_path.unescape_value().unwrap().into_owned();
            }
            Event::Eof => panic!("container.xml has no <rootfile>"),
            _ => {}
        }
    }
}
